export const developerProfile = {
  slug: 'aleksey-ermakov',
  name: 'Aleksey Ermakov',
  headline: 'TypeScript Backend Developer',
  description:
    'I build maintainable TypeScript services with clear boundaries, predictable data access, and reproducible development environments.',
  professionalLinks: [
    {
      label: 'GitHub',
      url: 'https://github.com/realfamousbae',
    },
    {
      label: 'Telegram',
      url: 'https://t.me/realfamousbae',
    },
  ],
  skills: [
    { name: 'TypeScript', category: 'Language' },
    { name: 'JavaScript', category: 'Language' },
    { name: 'Node.js', category: 'Backend' },
    { name: 'NestJS', category: 'Backend' },
    { name: 'REST API', category: 'API' },
    { name: 'GraphQL', category: 'API' },
    { name: 'WebSockets', category: 'API' },
    { name: 'gRPC', category: 'API' },
    { name: 'HTTP', category: 'API' },
    { name: 'SQL', category: 'Data' },
    { name: 'PostgreSQL', category: 'Data' },
    { name: 'Prisma ORM', category: 'Data' },
    { name: 'Redis', category: 'Data' },
    { name: 'CockroachDB', category: 'Data' },
    { name: 'SQLAlchemy', category: 'Data' },
    { name: 'Git', category: 'Tooling' },
    { name: 'Docker', category: 'Infrastructure' },
    { name: 'Docker Compose', category: 'Infrastructure' },
    { name: 'Kubernetes', category: 'Infrastructure' },
    { name: 'Express.js', category: 'Backend' },
    { name: 'Python', category: 'Language' },
    { name: 'SaaS', category: 'Platform' },
    { name: 'Flux', category: 'Frontend' },
    { name: 'Babel', category: 'Tooling' },
  ],
  experiences: [
    {
      company: 'Moscow Polytechnic University',
      position: 'TypeScript Developer',
      startPeriod: '2025-09',
      endPeriod: '2026-07',
      isCurrent: false,
      achievements: [
        'Developed and supported full-stack applications with TypeScript across the frontend and backend.',
        'Designed Node.js server architecture, REST APIs, business logic, and PostgreSQL data structures and migrations.',
        'Integrated frontend components with backend APIs and external services, including authorization, validation, error handling, and access control.',
        'Optimized client-server interaction and refactored existing code to improve modularity, readability, and maintainability.',
        'Containerized applications with Docker and used GitHub pull requests and code review for collaborative delivery.',
      ],
    },
    {
      company: 'Moscow Polytechnic University',
      position: 'TypeScript Backend Developer',
      startPeriod: '2024-09',
      endPeriod: '2025-07',
      isCurrent: false,
      achievements: [
        'Developed and supported backend services with TypeScript, Node.js, and NestJS.',
        'Designed modular service architecture, REST APIs, and server-side business logic for internal system components.',
        'Designed PostgreSQL data structures and migrations, optimized queries, and used Redis to cache frequently requested data.',
        'Integrated external APIs and implemented data validation, centralized error handling, and logging.',
        'Containerized services with Docker and collaborated through GitHub branches, pull requests, and code review.',
      ],
    },
  ],
  projects: [
    {
      name: 'Nearsy',
      description:
        'A hyperlocal, commission-free marketplace for Novokosino and Reutov, built as a service-oriented pilot with FastAPI services, versioned API and event contracts, PostgreSQL, and S3-compatible media storage.',
      url: 'https://github.com/realfamousbae/Nearsy',
      repositoryUrl: 'https://github.com/realfamousbae/Nearsy',
      technologies: [
        'TypeScript',
        'Python',
        'FastAPI',
        'PostgreSQL',
        'Redis',
        'MinIO (S3 API)',
        'Docker',
      ],
    },
    {
      name: 'Focus',
      description:
        'A privacy-focused web application for creating countdowns and synchronizing them across devices with calendar import support.',
      url: 'https://realfamousbae-focus.multihead-la-3424.chatgpt.site',
      repositoryUrl: 'https://github.com/realfamousbae/realfamousbae-focus',
      technologies: ['TypeScript', 'Next.js', 'React', 'Cloudflare D1'],
    },
    {
      name: 'Ploom',
      description:
        'A team-built service for creating personalized 3D souvenirs with AI. I owned the backend API, file handling, and AI service integration.',
      url: 'https://ploom-front.vercel.app',
      repositoryUrl: 'https://github.com/realfamousbae/ploom-backend',
      technologies: ['TypeScript', 'Node.js', 'Express', 'SQLite'],
    },
    {
      name: 'Hubble',
      description:
        'A cross-platform desktop productivity application migrated from Electron to Tauri 2 for a smaller runtime footprint and native packaging.',
      url: 'https://github.com/realfamousbae/hubble',
      repositoryUrl: 'https://github.com/realfamousbae/hubble',
      technologies: ['TypeScript', 'Tauri 2', 'Rust', 'React'],
    },
  ],
} as const;
